server:
  port: 9090

spring:
  application:
    name: brpl-kyc-demo
    
  datasource:
    url: jdbc:mysql://localhost:3306/brpl_kyc_data
    username: root
    password: Brpl@123
    
  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      
upload:
  image: images/