server:
  port: 9090

spring:
  application:
<<<<<<< HEAD
    name: brpl-kyc-demo
=======
    name: brpl-kyc-demo    
>>>>>>> c33a3474e4a60fbadbe1fff3ca2005bdd9c2a636
    
  datasource:
    url: jdbc:mysql://localhost:3306/brpl_kyc_data
    username: root
<<<<<<< HEAD
    password: Brpl@123
=======
    password: Mysql@2023
>>>>>>> c33a3474e4a60fbadbe1fff3ca2005bdd9c2a636
    
  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
<<<<<<< HEAD

=======
        
>>>>>>> c33a3474e4a60fbadbe1fff3ca2005bdd9c2a636
  servlet:
    multipart:
       max-file-size: 20MB
       max-request-size: 20MB
<<<<<<< HEAD
      
upload:
  image: images/
  
aws:      
  accessKey: "accessKey"
  secretKey: "secretKey"    
  region: "us-east-1"  
=======

      
   
upload:
  image: images/
  
  
>>>>>>> c33a3474e4a60fbadbe1fff3ca2005bdd9c2a636
