server:
  port: 9090

spring:
  application:
    name: brpl-kyc-demo
    
  datasource:
    url: jdbc:mysql://localhost:3306/brpl_kyc_data
    username: root
<<<<<<< HEAD
    password: Mysql@2023
=======
    password: Brpl@123
>>>>>>> b274fc9deaf7ad554f0e75d39cca1376a6ded153
    
  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      
upload:
  image: images/