server:
  port: 8080

com:
  kb:
    jwt:
      aws:
        userPoolId: "us-east-1_w5BD2MI1A"
        region: "us-east-1"
        
        
        
        
spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 1iadgmvsjtvnh553bk283mga5e
            client-secret: 11uhco71u0p6t2icmeftd89lgkb6nb8d3gki7h35d67tajat810k
            scope: openid, email, profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/cognito"
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuer-uri: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_w5BD2MI1A"   


cognito:
  userPoolId: us-east-1_w5BD2MI1A
                      

aws:
  cognito: 
    logoutUrl: "https://brpldomain01.auth.us-east-1.amazoncognito.com/logout"                    
    logout:
      success:
        redirectUrl: "http://localhost:8080/logout"        
  accessKey: AKIA2VTW7IIUA7LMUZA4
  secretKey: 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       
  region: "us-east-1"          
            